apiVersion: k8s.streamnative.io/v1alpha1
kind: SNConsole
metadata:
  name: sn-private-console
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud-console:v2.0.0
  webServiceUrl: http://brokers-broker:8080