apiVersion: k8s.streamnative.io/v1alpha1
kind: SNConsole
metadata:
  name: sn-private-console
  namespace: pulsar
spec:
  image: streamnative/sn-platform-console:v2.0.0-alpha15
  webServiceUrl: "http://brokers-broker.pulsar.svc.cluster.local:8080"