---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sn-operator
  namespace: operators
spec:
  channel: alpha
  name: sn-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: function-mesh-operator
  namespace: operators
spec:
  channel: alpha
  name: function-mesh
  source: operatorhubio-catalog
  sourceNamespace: olm
---
apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: pulsar-resources-operator 
  namespace: operators 
spec: 
  channel: alpha 
  name: pulsar-resources-operator 
  source: operatorhubio-catalog 
  sourceNamespace: olm