apiVersion: k8s.streamnative.io/v1alpha1
kind: PulsarCoordinator
metadata:
  name: private-cloud
  namespace: pulsar
spec:
  image: streamnative/private-cloud:3.0.1.4
---
apiVersion: zookeeper.streamnative.io/v1alpha1
kind: ZooKeeperCluster
metadata:
  name: private-cloud
  namespace: pulsar
spec:
  image: streamnative/private-cloud:3.0.1.4
  replicas: 1
  pod:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
    securityContext:
      runAsNonRoot: true
---
apiVersion: bookkeeper.streamnative.io/v1alpha1
kind: BookKeeperCluster
metadata:
  name: bookies
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud:3.0.1.4
  replicas: 3
  zkServers: zookeepers-zk:2181
  pod:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
  storage:
    reclaimPolicy: Delete
---
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: brokers
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
  annotations:
    cloud.streamnative.io/enable-pulsarctl-config: "true"
spec:
  image: streamnative/private-cloud:3.0.1.4
  replicas: 3
  zkServers: zookeepers-zk:2181
  config: 
    custom:
      PULSAR_PREFIX_managedLedgerDefaultEnsembleSize: "1"
      PULSAR_PREFIX_managedLedgerDefaultWriteQuorum: "1"
      PULSAR_PREFIX_managedLedgerDefaultAckQuorum: "1"
      PULSAR_PREFIX_oauthAudience: urn:sn:pulsar:sndev:kop-3-1
      PULSAR_PREFIX_oauthIssuerUrl: https://auth.test.cloud.gcp.streamnative.dev/
      PULSAR_PREFIX_oauthSubjectClaim: https://streamnative.io/username
      authenticationEnabled: "true"
      authenticationProviders: "io.streamnative.pulsar.broker.authentication.AuthenticationProviderOAuth"
      brokerClientAuthenticationPlugin: "org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2"
      brokerClientAuthenticationParameters: '{"audience":"urn:sn:pulsar:sndev:kop-3-1","issuerUrl":"https://auth.test.cloud.gcp.streamnative.dev/","privateKey":"file:///mnt/secrets/broker_client_credential.json","type":"client_credentials"}'
      authPlugin: "org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2"
      authParams: '{"audience":"urn:sn:pulsar:sndev:kop-3-1","issuerUrl":"https://auth.test.cloud.gcp.streamnative.dev/","privateKey":"file:///mnt/secrets/broker_client_credential.json","type":"client_credentials"}'
  pod:
    securityContext:
      runAsNonRoot: true
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    secretRefs:
    - mountPath: /mnt/secrets
      secretName: private-cloud
---
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarProxy
metadata:
  name: proxys
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
  annotations:
    cloud.streamnative.io/enable-pulsarctl-config: "true"
spec:
  image: streamnative/private-cloud:3.0.1.4
  replicas: 2
  brokerAddress: brokers-broker
  config: 
    custom:
      PULSAR_PREFIX_oauthAudience: urn:sn:pulsar:sndev:kop-3-1
      PULSAR_PREFIX_oauthIssuerUrl: https://auth.test.cloud.gcp.streamnative.dev/
      PULSAR_PREFIX_oauthSubjectClaim: https://streamnative.io/username
      authenticationEnabled: "true"
      authenticationProviders: "io.streamnative.pulsar.broker.authentication.AuthenticationProviderOAuth"
      brokerClientAuthenticationPlugin: "org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2"
      brokerClientAuthenticationParameters: '{"audience":"urn:sn:pulsar:sndev:kop-3-1","issuerUrl":"https://auth.test.cloud.gcp.streamnative.dev/","privateKey":"file:///mnt/secrets/broker_client_credential.json","type":"client_credentials"}'
      authPlugin: "org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2"
      authParams: '{"audience":"urn:sn:pulsar:sndev:kop-3-1","issuerUrl":"https://auth.test.cloud.gcp.streamnative.dev/","privateKey":"file:///mnt/secrets/broker_client_credential.json","type":"client_credentials"}'
  pod:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
    secretRefs:
    - mountPath: /mnt/secrets
      secretName: private-cloud
---
apiVersion: v1
kind: Secret
metadata:
  name: private-cloud
  namespace: pulsar
type: Opaque
data:
  broker_client_credential.json: <your_encoded_credential>