apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: private-cloud
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
<<<<<<< HEAD
  image: streamnative/private-cloud:3.1.1.1
=======
  image: streamnative/private-cloud:3.1.0.5
>>>>>>> origin/main
  zkServers: zookeepers-zk:2181
  replicas: 3
  pod:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
  config:
    protocolHandlers:
      mop:
        enabled: true
        proxyEnabled: true