apiVersion: k8s.streamnative.io/v1alpha1
kind: PulsarCoordinator
metadata:
  name: private-cloud
  namespace: pulsar
spec:
  image: streamnative/sn-platform-slim:2.10.3.4
  auditLog:
    categories:
      - Management
      - Describe