apiVersion: k8s.streamnative.io/v1alpha1
kind: PulsarCoordinator
metadata:
  name: private-cloud
  namespace: pulsar
spec:
  istio:
    revision: default
    trustDomain: cluster.local
---
apiVersion: zookeeper.streamnative.io/v1alpha1
kind: ZooKeeperCluster
metadata:
  name: private-cloud
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud:3.3.2.7
  replicas: 3
  pod:
    labels:
      sidecar.istio.io/inject: "true"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
  persistence:
    reclaimPolicy: Delete
---
apiVersion: bookkeeper.streamnative.io/v1alpha1
kind: BookKeeperCluster
metadata:
  name: private-cloud
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud:3.3.2.7
  replicas: 3
  zkServers: private-cloud-zk:2181
  pod:
    labels:
      sidecar.istio.io/inject: "true"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
  storage:
    reclaimPolicy: Delete
  autoRecovery:
    replicas: 1
    pod:
      labels:
        sidecar.istio.io/inject: "true"
      securityContext:
        runAsNonRoot: true
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
    conf:
      zkServers: private-cloud-zk:2181
---
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: private-cloud
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud:3.3.2.7
  replicas: 1
  zkServers: private-cloud-zk:2181
  config:
    clusterName: private-cloud
    advertisedDomain: httpbin.example.com
    serviceURLGenerationPolicy: FQDN
  pod:
    labels:
      sidecar.istio.io/inject: "true"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
  istio:
    enabled: true
    gateway:
      selector:        
        istio: ingressgateway
      tls:
        certSecretName: "httpbin-credential"
        mode: "simple"