{{- if .Values.watchNamespaces }}
{{- $namespaces := list }}
{{- $installNamespace := include "sn-operator.namespace" . }}
{{- range $namespace := split "," .Values.watchNamespaces }}
{{- if ne $namespace $installNamespace }}
  {{- $namespaces = append $namespaces $namespace }}
{{- end }}
{{- end }}
{{- range $namespace := append $namespaces (include "sn-operator.namespace" .) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ include "sn-operator.fullname" $ }}-manager-rolebinding-{{ $namespace }}'
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "sn-operator.clusterRoleManagerName" $ }}-{{ $namespace }}'
subjects:
  - kind: ServiceAccount
    name: {{ include "sn-operator.serviceAccountName" $ }}
    namespace: {{ include "sn-operator.namespace" $ }}
---
{{- end }}
{{- else }}
kind: ClusterRoleBinding
metadata:
  name: '{{ include "sn-operator.fullname" . }}-manager-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "sn-operator.clusterRoleManagerName" . }}'
subjects:
  - kind: ServiceAccount
    name: {{ include "sn-operator.serviceAccountName" . }}
    namespace: {{ include "sn-operator.namespace" .}}
  {{- end }}
