{{- define "sn-operator.rules" -}}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - pods/exec
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bookkeeper.streamnative.io
  resources:
  - bookkeeperclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bookkeeper.streamnative.io
  resources:
  - bookkeeperclusters/finalizers
  verbs:
  - update
- apiGroups:
  - bookkeeper.streamnative.io
  resources:
  - bookkeeperclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.functionmesh.io
  resources:
  - backendconfigs
  - functionmeshes
  - functions
  - sinks
  - sources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.istio.io
  resources:
  - authorizationpolicies
  - peerauthentications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - agentfunctions
  - apikeys
  - connections
  - consoles
  - coordinators
  - kafkaclusters
  - kafkaconnects
  - kafkarestproxies
  - mqttproxies
  - oxiaclusters
  - oxianamespaces
  - pfsqlclusters
  - pulsarcoordinators
  - snschemaregistries
  - storagecatalogs
  - unilinks
  - unilinkschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.streamnative.io
  resources:
  - agentfunctions/finalizers
  - apikeys/finalizers
  - connections/finalizers
  - consoles/finalizers
  - coordinators/finalizers
  - kafkaclusters/finalizers
  - kafkaconnects/finalizers
  - kafkarestproxies/finalizers
  - mqttproxies/finalizers
  - oxiaclusters/finalizers
  - oxianamespaces/finalizers
  - pfsqlclusters/finalizers
  - pulsarcoordinators/finalizers
  - snschemaregistries/finalizers
  - storagecatalogs/finalizers
  - unilinks/finalizers
  - unilinkschemas/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - agentfunctions/status
  - apikeys/status
  - connections/status
  - consoles/status
  - coordinators/status
  - kafkaclusters/status
  - kafkaconnects/status
  - kafkarestproxies/status
  - mqttproxies/status
  - oxiaclusters/status
  - oxianamespaces/status
  - pfsqlclusters/status
  - pulsarcoordinators/status
  - snschemaregistries/status
  - storagecatalogs/status
  - unilinks/status
  - unilinkschemas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - connectorcatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafkanodepools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafkas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - prometheuses
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - envoyfilters
  - gateways
  - serviceentries
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsarbrokerrevisions
  - pulsarbrokers
  - pulsarfunctionsworkers
  - pulsarproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsarbrokerrevisions/finalizers
  - pulsarbrokers/finalizers
  - pulsarfunctionsworkers/finalizers
  - pulsarproxies/finalizers
  verbs:
  - update
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsarbrokerrevisions/status
  - pulsarbrokers/status
  - pulsarfunctionsworkers/status
  - pulsarproxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zookeeper.streamnative.io
  resources:
  - zookeeperclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zookeeper.streamnative.io
  resources:
  - zookeeperclusters/finalizers
  verbs:
  - update
- apiGroups:
  - zookeeper.streamnative.io
  resources:
  - zookeeperclusters/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
