{{- define "sn-operator.rules" -}}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - bookkeeper.streamnative.io
  resources:
    - 'bookkeeperclusters'
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - cert-manager.io
  resources:
    - certificates
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - compute.functionmesh.io
  resources:
    - backendconfigs
    - functionmeshes
    - functions
    - sources
    - sinks
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - pods/exec
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8s.streamnative.io
  resources:
    - apikeys
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8s.streamnative.io
  resources:
    - apikeys/finalizers
  verbs:
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - apikeys/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - connectorcatalogs
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - k8s.streamnative.io
  resources:
    - consoles
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8s.streamnative.io
  resources:
    - consoles/finalizers
  verbs:
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - consoles/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - kafkaconnects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.streamnative.io
  resources:
  - kafkaconnects/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - kafkaconnects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - mqttproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.streamnative.io
  resources:
  - mqttproxies/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - mqttproxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - oxiaclusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8s.streamnative.io
  resources:
    - oxiaclusters/finalizers
  verbs:
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - oxiaclusters/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - oxianamespaces
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8s.streamnative.io
  resources:
    - oxianamespaces/finalizers
  verbs:
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - oxianamespaces/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - pfsqlclusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8s.streamnative.io
  resources:
    - pfsqlclusters/finalizers
  verbs:
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - pfsqlclusters/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - pulsarcoordinators
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8s.streamnative.io
  resources:
    - pulsarcoordinators/finalizers
  verbs:
    - update
- apiGroups:
    - k8s.streamnative.io
  resources:
    - pulsarcoordinators/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - networking.istio.io
  resources:
    - destinationrules'
    - 'envoyfilters'
    - 'gateways'
    - 'proxyconfigs'
    - 'serviceentries'
    - 'sidecars'
    - 'virtualservices'
    - 'workloadentries'
    - 'workloadgroups'
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - pulsar.streamnative.io
  resources:
    - 'pulsarbrokerrevisions'
    - 'pulsarbrokers'
    - 'pulsarfunctionsworkers'
    - 'pulsarproxies'
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - security.istio.io
  resources:
    - 'authorizationpolicies'
    - 'peerauthentications'
    - 'requestauthentications'
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - zookeeper.streamnative.io
  resources:
    - 'zookeeperclusters'
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - authentication.k8s.io
  resources:
    - tokenreviews
  verbs:
    - create
- apiGroups:
    - authorization.k8s.io
  resources:
    - subjectaccessreviews
  verbs:
    - create
- apiGroups:
  - k8s.streamnative.io
  resources:
  - unilinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.streamnative.io
  resources:
  - unilinks/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - unilinks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - unilinkschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.streamnative.io
  resources:
  - unilinkschemas/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.streamnative.io
  resources:
  - unilinkschemas/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
