apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "sn-operator.namespace" . }}
  labels:
    {{- include "sn-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: sn-operator-controller-manager-metrics-service
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "sn-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
